version: '3.8'

services:

  wsgiserver:
    build: .
    restart: always
    command: daphne djangoProjectDiagnostics.asgi:application -b 0.0.0.0 -p 8000
    ports:
      - '0.0.0.0:8000:8000'
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app/

  postgres:
    image: postgres:15
    container_name: local_pgdb
    restart: always
    environment:
      POSTGRES_DB: "diagnostics"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
        - 6379:6379

volumes:
  db: